#ifndef DPUSHBUTTON_GLOBAL_H
#define DPUSHBUTTON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DPUSHBUTTON_LIBRARY)
#  define DPUSHBUTTONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DPUSHBUTTONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DPUSHBUTTON_GLOBAL_H
